src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $postAt;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post")
     */
    private $comments;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     */
    private $Author;

    /**
     * @ORM\ManyToOne(targetEntity=Subject::class, inversedBy="posts")
     */
    private $subject;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPostAt(): ?\DateTimeInterface
    {
        return $this->postAt;
    }

    public function setPostAt(\DateTimeInterface $postAt): self
    {
        $this->postAt = $postAt;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getSubject(): ?subject
    {
        return $this->subject;
    }

    public function setSubject(?subject $subject): self
    {
        $this->subject = $subject;

        return $this;
    }
}

templates/home/create.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}Create{% endblock %}

{% block body %}

{{ form_start(form) }}
	{{ form_widget(form) }}
	<input type="submit" value="Publier" formnovalidate>
{{ form_end(form) }}
{% endblock %}	

templates/home/edit.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}Create{% endblock %}

{% block body %}
<div class="container">
	{{ form_start(form) }}
		{{ form_widget(form) }}
		<input class="btn btn-primary" type="submit" value="Edit">
	{{ form_end(form) }}
</div>
{% endblock %}	

templates/home/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}Forum{% endblock %}

{% block body %}

{{ include('layouts/_flash_message.html.twig') }}

<div class="container">
	<h1 class="h3 mt-5">Forums</h1>
	{% if is_granted('ROLE_ADMIN') %}
		<a href="{{ path('app_newForum') }}" class="h5">Nouveau Forum</a>
	{% endif %}
	{% for forums in forums %}
		<table class="table table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">{{ forums.title }} {% if is_granted('ROLE_ADMIN')%}<a href="{{ path('app_subject_create') }}">- Nouveau sujet</a>{% endif %}</th>
		    </tr> 
		  </thead>
		  <tbody>
		  {% for subjects in subjects %}
		    <tr>
		   	  {% if subjects.forum == forums.id %}
			      <td><a href="{{ path('app_subject', {'id': subjects.id }) }}">{{ subjects.title }}</a></td>
			  {% endif %}
		    </tr>
		  {% endfor %} 
		  </tbody>
		</table>
	{% endfor %}
</div>
<hr style="margin: auto; margin-top: 50px;">



{% endblock %}

templates/home/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}Create{% endblock %}

{% block body %}

{{ include('layouts/_flash_message.html.twig') }}

<div class="container mt-5">

<h1>{{ post.title }}</h1>
<p>{{ post.message }}</p>
<small>{{ post.author }} - {{ post.postAt|date("l d F - H:i") }}  
	{% if is_granted('ROLE_ADMIN') %}
		<a href="{{ path('app_delete', {'id': post.id}) }}"> Delete</a>
	{% endif %}
	{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
		{% if post.author == app.user.username %}
			<a href="{{ path('app_delete', {'id': post.id}) }}"> Delete</a>
			<a href="{{ path('app_edit', {'id': post.id}) }}">- Edit</a>
		{% endif %}
	{% endif %}
</small>

<hr>
{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
<h2>Commentaires ({{ comments|length }}) - Ajouter un commentaire</h2>
{{ form_start(form) }}
{{ form_widget(form) }}
<input type="submit" value="envoyer" formnovalidate>
{{ form_end(form) }}
{% else %}
<h2>Commentaires ({{ comments|length }})</h2>
<p><a href="{{ path('app_register') }}">Sign in or login</a> to comment</p>
{% endif %}

<hr>
	{% for comments in comments|sort|reverse %}	
		<h4>{{ comments.author }}</h4>
		<p>{{ comments.comment }}</p>
		<small>{{ comments.postAt|date("l d F - H:i") }}</small>
		<hr>
	{% endfor %}

	

</div>	

{% endblock %}	